### ISSUE TITLE
it support  Loongarch64？

### ISSUE THREAD

**Issue by geffzhang** [tryphotino/photino.Native#102]
it support  Loongarch64？
.NET 7 support Loongarch64  https://github.com/dotnet/runtime/tree/main/src/coreclr/vm/loongarch64
http://www.loongnix.cn/zh/api/dotnet/downloads-7.0.0-ea1/index.html

**Comment by philippjbauer** [comment]
You can compile the Photino.Native package for this platform but we do not support this architecture.

Currently we release the native package compiled for Windows, Linux and macOS on both x86-64 and ARM64 architectures.

There are no plans to expand support beyond those operating systems and architectures.
