### ISSUE TITLE
Using Fixed Version runtime distribution mode

### ISSUE THREAD

**Issue by RonenNess** [tryphotino/photino.Native#105]
Hi,
Is it possible to init WebView from a folder path, ie fixed version runtime mode?

More details here:
[https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)

Sorry if I missed something obvious, but I didn't find a way with Photino :)

Thanks!

**Comment by philippjbauer** [comment]
Scratch that, we have already implemented a method that lets you set the runtime path.

See `Photino.NET/PhotinoWindow.NET.cs`:
```
/// <summary> Set runtime path for WebView2 so that developers can use Photino on Windows using the "Fixed Version" deployment module of the WebView2 runtime. See https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution </summary>
        public PhotinoWindow Win32SetWebView2Path (string data) {
            if (IsWindowsPlatform)
                Invoke(() => Photino_setWebView2RuntimePath_win32(_nativeType, data));
            else
                Log("Win32SetWebView2Path is only supported on the Windows platform");

            return this;
        }
```

You will still have to contend with any differences in the API that is used by the native code in Windows, and potentially missing features in macOS and Linux.

**Comment by RonenNess** [comment]
Thank you, I'll try what you suggested :)
