### ISSUE TITLE
NuGet package for Photino.Native contains no dylib for osx-arm64 

### ISSUE THREAD

**Issue by CaffeinatedCoder** [tryphotino/photino.Native#107]
The current version of Photino.Native's NuGet package contains a dylib compiled for platform x64 inside the folder *runtimes/native/osx-arm64*, so debugging or executing Photino applications on M1 MacBooks simply fails.

**Comment by ottodobretsberger** [comment]
We are aware of this. We are actually currently working on this as we speak. We will update and push the changes once we have concluded our efforts on this issue.
@philippjbauer would know more up top date details on that probably.

**Comment by 13474657423** [comment]
使用file Photino.Native.so看这个文件是arm64还是X64的文件，如果是X64的文件你需要到https://codeload.github.com/tryphotino/photino.Native/zip/refs/tags/v2.4.1下载源代码，然后编译程arm64的文件，拷贝到文件中即可

**Comment by MikeYeager** [comment]
@13474657423 We now have a universal build for Mac that works on both x64 and Arm-64. For Mac, the file extension is .dylib. For Windows it's .dll and for Linux, it's .so.
