### ISSUE TITLE
Cancel save file dialog, will crash the application

### ISSUE THREAD

**Issue by JerryJian** [tryphotino/photino.Native#113]
https://github.com/tryphotino/photino.Native/blob/94a9adace478eee339f305ebe42bf931c94529af/Photino.Native/Photino.Linux.Dialog.cpp#L104C11-L104C11

Cancel save file dialog, the method returns NULL, the above code will cause Segmentation fault.

**Comment by MikeYeager** [comment]
Good catch. thank you. We have just checked in a change that fixes this. It will be in the next version.
