### ISSUE TITLE
Is it possible to wrap Photino as an Avalonia control?

### ISSUE THREAD

**Issue by charleypeng** [tryphotino/photino.Native#114]
I am so interested in this project, and I also using Avalonia  for linux desktop development. If the Photino and Avalonia hybrid (like webview in MAUI) app is a possible thing, please give me some hint on how to do this,  I think the first thing I might be doing is to read the code of Photino Native , thanks!

**Comment by MikeYeager** [comment]
Photino is a wrapper for a webview control that places the control in a native window.
