### ISSUE TITLE
webkit_settings_set_disable_web_security

### ISSUE THREAD

**Issue by anan1213095357** [tryphotino/photino.Native#118]
gcc -std=c++11 -shared -DOS_LINUX Exports.cpp Photino.Linux.cpp -o x64/$(buildConfiguration)/Photino.Native.so `pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0 libnotify` -fPIC
buildConfiguration: command not found
Photino.Linux.cpp: In member function ‘void Photino::set_webkit_settings()’:
Photino.Linux.cpp:771:2: error: ‘webkit_settings_set_disable_web_security’ was not declared in this scope; did you mean ‘webkit_settings_set_enable_webrtc’?
  771 |  webkit_settings_set_disable_web_security(settings, !_webSecurityEnabled);   //webkit default: False
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |  webkit_settings_set_enable_webrtc

**Comment by MikeYeager** [comment]
@anan1213095357 The latest makefile updated to webkit2gtk-4.1. I think you need to update your build command. Please let us know how it goes.

**Comment by jammerxd** [comment]
https://webkitgtk.org/reference/webkit2gtk/2.5.1/WebKitWebContext.html#webkit-web-context-set-tls-errors-policy

It looks like we need to be setting the TLS errors policy.
