### ISSUE TITLE
Possible to use this directly instead of Photino.NET?

### ISSUE THREAD

**Issue by R-Bower** [tryphotino/photino.Native#119]
We have a use case internally that calls for eliminating the C# layer of Photino.NET and using C++ directly.  Is it possible to use this native module to create and package applications without a need for the .NET dependency?

**Comment by philippjbauer** [comment]
Generally yes. But it depends somewhat on how you want to use it and what your use case is. Would you mind elaborating a little bit more?

**Comment by R-Bower** [comment]
We're looking to implement an Electron-like application using Angular or React.  We want to avoid Electron due to its bloat, and Photino looks like an excellent alternative. The issue is that we need to package it up with our C++ backend.  We have C++ developers that want to avoid C# completely.  

- The application consists of a C++ API that can invoke OS-specific libraries and dlls.  
- The frontend would need to be able to send messages to and receive messages from this backend.  
- The application would need to be packable into an executable for installation on target machines.
