### ISSUE TITLE
SIGSEGV calling gdk_window_set_keep_above 

### ISSUE THREAD

**Issue by jjolidon** [tryphotino/photino.Native#124]
Hello all,

I have an issue running a small demo app in linux, receiving SIGSEGV when starting. The app is a photino.net app, but I believe the issue is in the underlying native lib.

I'm not sure what you need to reproduce, and my source code is pretty minimalistic, so I'll just attach it here.

```cs
using System.Drawing;
using PhotinoNET;

namespace Demo
{
    internal class Program
    {
        [STAThread]
        private static void Main(string[] args)
        {
            var window = new PhotinoWindow()
                .SetTitle("Borderless browser")
                .SetResizable(false)
                .SetUseOsDefaultSize(false)
                .SetUseOsDefaultLocation(false)
                .SetChromeless(true)
                .SetSize(new Size(300, 300))
                .SetTop(100)
                .SetLeft(100)
                .SetTopMost(true);
            
            window.Load(new Uri("https://www.example.org"));
            window.WaitForClose();
        }
    }
}
```

This happens (on linux) whether I compile on linux or windows, and removing the `SetTopMost` call is sufficient to resolve that specific issue.

Update: running on .net 6.0.26 in Ubuntu 22.04 LTS

Any help on this would be appreciated, thank you in advance!

**Comment by philippjbauer** [comment]
Fixed with https://github.com/tryphotino/photino.Native/commit/fee5803aa73762a61ecdc62bafae0818e8487fbe
