### ISSUE TITLE
libwebkit2gtk-4.0 not available in Ubuntu 24.04

### ISSUE THREAD

**Issue by lixinyang123** [tryphotino/photino.Native#133]
libwebkit2gtk-4.1 is default on Ubuntu 24.04

```bash
🔋 100% ❯ sudo apt search libwebkit2gtk 

libwebkit2gtk-4.0-doc/noble-updates,noble-security 2.44.2-0ubuntu0.24.04.1 all
  WebKitGTK documentation (transitional dummy package)

libwebkit2gtk-4.1-0/noble-updates,noble-security,now 2.44.2-0ubuntu0.24.04.1 amd64 [installed]
  Web content engine library for GTK

libwebkit2gtk-4.1-dev/noble-updates,noble-security 2.44.2-0ubuntu0.24.04.1 amd64
  Web content engine library for GTK - development files
```

got an error when i build

```bash
🔋 100% ❯ dotnet run
Unable to load shared library 'Photino.Native' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
```

I need to manually install libwebkit2gtk-4.0 to run

**Comment by LauraWebdev** [comment]
Yeah it seems like recent Linux OS don't ship with 4.0 anymore. Fedora also has switched to webkit2gtk-4.1

**Comment by IceReaper** [comment]
Manjaro - same here.

**Comment by philippjbauer** [comment]
That's correct for development purposes. You have to install the 4.0 version and package the correct one in your package.

https://github.com/tryphotino/photino.Samples/tree/master/Photino.PublishPhotino/PublishPhotino

**Comment by LauraWebdev** [comment]
@philippjbauer This should definitely be documented somewhere then, because otherwise people will just be confused why not even the demo projects work out of the box.
