### ISSUE TITLE
Windows arm64

### ISSUE THREAD

**Issue by minzdrav** [tryphotino/photino.Native#146]
Hi Photino team
This project looks very interesting. I'm considering it for my next project. As I understand from the readme, there is only x64 version right now.
Is it possible to build the arm64 version?
I'm using a laptop with a snapdragon x elite processor as my main development machine right now. It's powerful and the battery life is really good. It would be super cool to have native photino build.

Thank you.

**Comment by bluerockface** [comment]
It actually works fine on win-arm64. I too am using snapdragon x. 

see below:
https://nuget.info/packages/Photino.Native/3.2.3
![image](https://github.com/user-attachments/assets/f475d637-60f8-45d5-9684-7b236cb785eb)

**Comment by minzdrav** [comment]
@bluerockface Thank you! It's not clear from GitHub and NuGet pages.
