### ISSUE TITLE
WebKit?

### ISSUE THREAD

**Issue by ChristianWeyer** [tryphotino/photino.Native#15]
Hi there :-)

Pleased to see this effort, thank you for that!

A quick question, as I stumbled over it in the docs:
_"Photino uses the OSs built-in WebKit-based browser control for Windows, macOS and Linux"_

Which WebKit-based OS browsers do we have in Windows and Linux?

Cheers!
-Christian

**Comment by MikeYeager** [comment]
Hi Christian! macOS uses Safari’s WKWebView and on Linux it uses WebKitGTK+ 2 (which is installed on many configurations).

**Comment by ChristianWeyer** [comment]
Yes, exactly. But not on Windows ;-)
