### ISSUE TITLE
Add support for Linux ARM64

### ISSUE THREAD

**Issue by todosrc** [tryphotino/photino.Native#17]
it support Arm64 /Raspbery PI ?

**Comment by philippjbauer** [comment]
Currently it is only compiled for x68. I know that .NET runs on Raspian. We would have to try and compile on Raspian and if that checks out, build a pipeline to automate the build.

Thanks for your input @todosrc!

**Comment by todosrc** [comment]
i try on Raspbery PI 3 , this is the result : 

pi@raspberrypi:~/Desktop/testbrowser $ dotnet HelloPhotino.NET.dll
Creating new PhotinoWindow instance.
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'Photino.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libPhotino.Native: cannot open shared object file: No such file or directory
   at PhotinoNET.PhotinoWindow.Photino_ctor(String title, IntPtr parentPhotinoNET, WebMessageReceivedDelegate webMessageReceivedCallback, Boolean fullscreen, Int32 x, Int32 y, Int32 width, Int32 height)
   at PhotinoNET.PhotinoWindow..ctor(String title, Action`1 configure, Int32 width, Int32 height, Int32 left, Int32 top, Boolean fullscreen)
   at HelloPhotinoApp.Program.Main(String[] args) in E:\MyIOT\photino.Samples-master\photino.Samples-master\Photino.HelloPhotino.NET\Program.cs:line 55
Aborted

**Comment by adeotek** [comment]
Any news or maybe an ETA for ARM/Raspberry Pi support?

**Comment by MikeYeager** [comment]
No ETA at this point. We're working hard to get V2 working on Windows, Linux and macOS. It would be great to have someone from the community try to compile for RasPi when that's ready. You may have a long wait for us to get around to it.

**Comment by sanme98** [comment]
I have compiled the source code using the command below in Raspbian ARM 64 bit. But I still unable to make it works correctly though the program was running. Photino just displayed _The URL can’t be shown_, I was using the _dotnet new photinoapp -o photinoapp_ without any code changes.
 
gcc -std=c++11 -shared -DOS_LINUX Exports.cpp Photino.Linux.cpp -o x64/Photino.Native.so \`pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0\` -fPIC

![image](https://user-images.githubusercontent.com/5364763/131860553-ae389345-ec22-4ac4-a218-9b739782323c.png)

**Comment by sanme98** [comment]
I think the _The URL can’t be shown_ is same issue with this https://github.com/tryphotino/photino.Samples/issues/18.

I have tried new Uri("https://www.google.com"), it has same error too.

**Comment by todosrc** [comment]
@sanme98  i think the URL [issue    ](https://github.com/tryphotino/photino.Samples/issues/18)is already close , can you retest on PI ?

**Comment by sanme98** [comment]
I got the error below after install Templates::2.0.1 on PI 64 bits. The program exited after I clicked Close button.

![image](https://user-images.githubusercontent.com/5364763/141611892-d12db145-8f8e-4ad5-b66d-4f75a09239ea.png)

**Comment by MikeYeager** [comment]
@sanme98 This error indicates a mismatched version between the .Native code and the .NET code. Please make sure you're working with the latest packages and/or source code.

**Comment by sanme98** [comment]
@MikeYeager I have no idea now, I created a new project by using the latest template also the same error. 

> dotnet new -i TryPhotino.VSCode.Project.Templates\
> && dotnet new photinoapp -o MyPhotinoApp\
> && cd MyPhotinoApp\
> && dotnet run

After that, I have even added the native library package manually. The same error too.

> dotnet add package Photino.Native --version 2.1.3

csproj content
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.Native" Version="2.1.3" />
    <PackageReference Include="Photino.NET" Version="2.0.13" />
  </ItemGroup>

  <ItemGroup>
    <None Update="wwwroot\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

Will try to debug if I have some time in future & know how to debug native lib.

**Comment by MikeYeager** [comment]
@sanme98 The newest version of Photino.Native is indeed 2.1.3, however the newest version of Photino.NET is 2.1.10, not 2.0.13. I believe that's where the issue lies. Please update Photino.NET. Cheers!

**Comment by todosrc** [comment]
@sanme98  Cheers!

**Comment by GermanJack** [comment]
Hey, sounds great.
I also want to use Photino on a Raspberry PI.
Can you please share your running version somehow?

**Comment by mdemler** [comment]
Also interested in this capability.

**Comment by MollsAndHersh** [comment]
I too am interested in trying to get a Photino app running on a Pi 4 or Pi Pico or Pi Zero.  Any ETA or plans for this soon?

**Comment by GermanJack** [comment]
Meanwhile I compiled it by myself for ARM32.
It runs on my Raspberry PI3B+ without problems.
It is part of this project archive: http://web.freescoreboard.org/download/FreeScoreBoard9_Beta1.tar.gz

**Comment by GermanJack** [comment]
Dear Mike,
this is the compile command I have used:
gcc -std=c++11 -shared -DOS_LINUX Exports.cpp Photino.Linux.cpp -o x64/Photino.Native.so `pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0` -fPIC

I compiled it directly on my Raspberry 3B+ with the 32Bit Raspberry OS.
Well, I am not so familiar with c++.
In the beginning I had some errors and packages to setup on by device (like gtk).
I just followed the messages and finally I got the compilation.

Great Project, Thanks

**Comment by bmclapham1973** [comment]
I compiled photino.Native on Raspberry Pi OS (PI4) both 32bit(linux-arm) and 64bit(linux-arm64) with no issues.

Next, I am working to compile photino.Native on M1 Mac mini (osx-arm64).

It would be excellent to add pipelines for each of the following to the repo!
-linux-arm
-linux-arm64
-osx-arm64

**Comment by liguobao** [comment]
Looking forward to this feature

**Comment by philippjbauer** [comment]
Photino.NET v2.5.0 was just released with support for ARM64 on Windows, macOS and Linux. Windows and Linux (Debian) ARM64 tested in VM on Apple Silicon.

For anyone interested in using this on other platforms than Debian-related Linux distros (Raspberry Pi, SuSe, RedHat, etc), feedback is very much appreciated.
