### ISSUE TITLE
[Linux] Make developer tools available

### ISSUE THREAD

**Issue by MikeYeager** [tryphotino/photino.Native#21]
Developer tools not available in Linux (Mac?) web viewer controls. See Photini.Linux.cpp line 125. https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebInspector.html

| Can confirm, developer tools are available in macOS.
| - Philipp

**Comment by philippjbauer** [comment]
Is implemented in Linux in Native 1.1.1
