### ISSUE TITLE
Photino.HelloPhotino.AdvancedNET crashes with undefined symbol: basic_ostringstream

### ISSUE THREAD

**Issue by ronnieholm** [tryphotino/photino.Native#57]
On Ubuntu 18.04, Photino.HelloPhotino.AdvancedNET sample (and others), clicking the "Call .NET via text passed to a memory buffer" button causes an app crash. The Photino window disappears and in the terminal the app prints:

```
/tmp/photino.Samples/Photino.HelloPhotino.AdvancedNET/bin/Debug/net5.0/HelloPhotino.AdvancedNET: symbol lookup error:
/tmp/photino.Samples/Photino.HelloPhotino.AdvancedNET/bin/Debug/net5.0/runtimes/linux-x64/native/Photino.Native.so: 
undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
```

Demangling the undefined symbol:

    std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()

**Comment by ottodobretsberger** [comment]
We haven't seen that issue come up on our end, and neither has any other Linux user reported it. 
Probably needs some more investigation, maybe differences in framework or OS installations?

**Comment by ottodobretsberger** [comment]
This problem we believe should no longer be there in the newly released Photino v2 version. Please give it a try and let us know if you see anything unexpected.

**Comment by mikelevins** [comment]
I just installed .NET SDK 5.0.202 on Ubuntu 18.04.6, and then installed Photino using:

dotnet new -i TryPhotino.VSCode.Project.Templates

I then did 

dotnet new photinoapp -o MyPhotinoApp
cd MyPhotinoApp
dotnet run

and I saw the same issue reported above.

For reference, here's the trace of the run from the terminal:

mikel@mars:~/Laboratory/photino/MyPhotinoApp$ dotnet run
Photino.NET: "Photino".SetTitle(Photino for .NET Demo App)
Photino.NET: "Photino for .NET Demo App".SetUseOsDefaultSize(False)
Photino.NET: "Photino for .NET Demo App".SetSize({Width=600, Height=400})
Photino.NET: "Photino for .NET Demo App".Center()
Photino.NET: "Photino for .NET Demo App".SetResizable(False)
Photino.NET: "Photino for .NET Demo App".Load(wwwroot/index.html)
Photino.NET: "Photino for .NET Demo App".Load(file:///home/mikel/Laboratory/photino/MyPhotinoApp/wwwroot/index.html)
Photino.NET: "Photino for .NET Demo App".SendWebMessage(Received message: "Hi .NET! 🤖")
/home/mikel/Laboratory/photino/MyPhotinoApp/bin/Debug/net5.0/HelloPhotino.NET: symbol lookup error: /home/mikel/Laboratory/photino/MyPhotinoApp/bin/Debug/net5.0/runtimes/linux-x64/native/Photino.Native.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
