### ISSUE TITLE
Calling SetIconFile crashes app on macOS

### ISSUE THREAD

**Issue by philippjbauer** [tryphotino/photino.Native#60]
Calling SetIconFile from a razor page crashes the application. I assume the way that the icon is set (not confirmed working in any other way either) is not correct yet? 

https://github.com/tryphotino/photino.Samples/blob/7f4481778f827f78003a74593017f9896fc1a01f/Photino.HelloPhotino.Blazor/Pages/Index.razor#L4

Related PR: https://github.com/tryphotino/photino.NET/pull/30
Related Blazor Issue: https://github.com/tryphotino/photino.Blazor/issues/12

**Comment by hbxtlhx** [comment]
You are right, I also encountered this problem. After commenting these codes, it ran. Great! 

//Invoke(() => Photino_SetIconFile(_nativeInstance, Path.GetFullPath(path)));

**Comment by hbxtlhx** [comment]
You are right, I also encountered this problem. After commenting these codes, it ran. Great! 

//Invoke(() => Photino_SetIconFile(_nativeInstance, Path.GetFullPath(path)));

**Comment by ottodobretsberger** [comment]
This shouldn't crash under v2 unless a bad path or a bad image is provided. 
But also this doesn't do anything in macOS as there's no icon in the title bar. 
.ico files should only be used for Windows.
