### ISSUE TITLE
macOS: input tag does not open file picker

### ISSUE THREAD

**Issue by BarryNolte** [tryphotino/photino.Native#67]
To reproduce, using the default **photinoapp** application, place the following in the default index.html file:

<input type="file" />

* Run
* Press "Choose File" button

Result: Nothing happens
Expected: File picker to open

macOS Catalina - 10.15.7

Verified this works as expected on Windows.  Also it fails with a Xamarin.Mac app with an embedded WKWebView, so I'm thinking it's either impossible, or the WKWebView is not being created with the proper security context (which for the life of me can't figure out how to change).  Opening the index.html file in macEdge or Safari also works as expected.

**Comment by ottodobretsberger** [comment]
This appears to be related to WebKit, not necessarily to Photino. We will add it to our list of things to look into though.

**Comment by philippjbauer** [comment]
This works in 2023 :)
Tested in macOS Ventura with Photino.NET v2.4.1 and latest (2.5.0).
