### ISSUE TITLE
Linux PhotinoWindow appears to be missing minimize/maximize icons

### ISSUE THREAD

**Issue by tomlm** [tryphotino/photino.Native#78]
On windows
![image](https://user-images.githubusercontent.com/17789481/149631424-2bcda58b-eeb1-4205-97d3-d9ae6a09aa04.png)

on Linux 
![image](https://user-images.githubusercontent.com/17789481/149631384-eac7ac50-ee9b-41df-b0b5-e0a4664cfbdb.png)

I'm running this on ubuntu via WSL...

I don't have access to mac, so don't know what it does there.

**Comment by MikeYeager** [comment]
I experience this in WSLg also, however, it's not a problem on an Ubuntu machine. Please see this thread which indicates that the issue is with GTK and GNOME and offers some work-arounds: https://github.com/microsoft/wslg/issues/563
