### ISSUE TITLE
SetUserAgent Support

### ISSUE THREAD

**Issue by kinosang** [tryphotino/photino.Native#84]
Allow user to set custom User-Agent

**Comment by kinosang** [comment]
@MikeYeager to tracking visitor informations. and use injected functions from web pages when open from inner webview.

**Comment by MikeYeager** [comment]
Great. Thank you @kinosang. This is something we can probably do, but will have to do for each of the 3 browser controls used on the 3 OSs. It would be great if someone from the community could help us out with this.

**Comment by philippjbauer** [comment]
@kinosang This can be set with the new `SetUserAgent()` method during PhotinoWindow startup in v2.5.0:

```cs
        PhotinoWindow window = new PhotinoWindow()
            .SetTitle("Photino Testing")
            .SetUserAgent("Photino Testing")
            /// more options ...
            .LoadRawString("Hello World!");
```
