### ISSUE TITLE
Is ubuntu 18.04 not supported?

### ISSUE THREAD

**Issue by NothingToHere** [tryphotino/photino.Native#85]
CFLAGS=-std=c++2a in the library's makefile.

**Comment by NothingToHere** [comment]
Photino.NET: "Photino.Blazor App".SendWebMessage(__bwv:["BeginInvokeJS",2,"Blazor._internal.attachWebRendererInterop","[0,{\u0022__dotNetObject\u0022:1},{},{}]",3,0])
/home/auser/RiderProjects/MyApp/MyApp/bin/Debug/net6.0/MyApp: symbol lookup error: /home/auser/RiderProjects/MyApp/MyApp/bin/Debug/net6.0/runtimes/linux-x64/native/Photino.Native.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev

**Comment by NothingToHere** [comment]
The error disappeared when I changed CFLAGS=-std=c++2a to CFLAGS=-std=c++17

**Comment by MikeYeager** [comment]
It appears Ubuntu 18.04 requires the older C++ compiler? Good to know for those running 18.04. Thank you.
