### ISSUE TITLE
Mac ARM64 (M1) support

### ISSUE THREAD

**Issue by sgacond** [tryphotino/photino.Native#92]
Hi Photino Team

I'm very interessted in using photino for my app. Unfortunately it seems, the native bits for osx-arm64 are missing.

I did a quick-and-dirty try and was able to compile the mac native parts to ARM64 (with your existing makefile).
After bringing it over to the output dir of my little test app, i was able to run it on my M1 mac.

I think the change wouldn't be too large (.nuspec and CI pipeline).
Are there any plans to add this in the near future? Or would you appreciate a PR? It would maybe not be possible without your support (because of the Az-DevOps pipeline), would it?

Maybe also related to #17 ?

Id be happy to contribute if possible.

**Comment by bmclapham1973** [comment]
Can you share the cmd line you used to compile to osx-arm64? I didn't have the same result as you when I attempted this.

**Comment by sgacond** [comment]
Sure! I used their build script. Just make shure you're CWD is the repository root, otherwise it won't work:
<img width="814" alt="image" src="https://user-images.githubusercontent.com/9912606/174352978-c4862f4a-949a-4906-ba15-f6bc21ccf844.png">
Its using clang under the hood... 
I am not that used to the new universal and non universal stuff for native compilation yet. But i think it should be possible to generate a universal dylib working on osx-x64 and osx-arm64. Then the change would be in the .nuspec only.

**Comment by sgacond** [comment]
@MikeYeager Thank you very much for your feedback.
I helped myself compiling it manually and including the binary in my project for the moment.
Will keep monitoring it and hoping azure devops gets an osx-arm64 runner sometimes.

**Comment by sgacond** [comment]
Hello Again! I just wanted to check back if there was some progress in the meantime and upgraded to the latest versions (and removed my special dylib loading). And i found a very strange behaviour:

In Photino.Native 2.2.3, the included osx-arm64 dylib is in the correct format, but in the latest version (2.3.2), the dependency broke again:

![image](https://user-images.githubusercontent.com/9912606/219761444-84a31067-2562-4d76-878b-96665d0dc5ec.png)

... save, dotnet build ...

![image](https://user-images.githubusercontent.com/9912606/219761795-c5804e9a-9bf6-41bf-b2da-a553bc84135c.png)

Seems like something broke again in the build?
The issue is reproducable using your simple HelloPhotino.NET sample.

**Comment by philippjbauer** [comment]
@sgacond Thank you for pointing this out! We ran some tests and concluded that the Azure Pipeline VMs we configured for the ARM builds are not ARM machines despite the way we configured them. I have manually compiled the ARM versions of the native package on my M1 (Windows 11 and Linux via VM on the machine) and bundled everything into a pre-release version of the Photino.NET package (see attachment). 

Could you please install this package from a local package source and verify for me that this solves your problem?

You can save this file in a new folder `LocalPackages` in your project directory and add the following to a file called `nuget.config`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="LocalPackages" value=".\LocalPackages" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

Btw, you don't need the Photino.Native package as a reference in your project, Photino.NET itself is dependent on the package and will make it available to your project.

[Photino.NET.2.3.3-pre.nupkg.zip](https://github.com/tryphotino/photino.Native/files/10825435/Photino.NET.2.3.3-pre.nupkg.zip)

**Comment by sgacond** [comment]
Hi @philippjbauer 

Thank you very much for reaching out!
I set up a test project with a local package source, but wasn't able to restore because the transitive dependency to `Photino.Native.2.3.3-pre` was missing.

Package Reference on the pre version:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/9912606/221342228-4e4bec14-2c9b-4310-9f0b-28db56f6264e.png">

Local nuget.config:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/9912606/221342162-378fb014-41d2-428e-8953-20f7b594e764.png">

Restore error:
<img width="869" alt="image" src="https://user-images.githubusercontent.com/9912606/221342167-b524cfeb-afb5-44f6-8043-c5ac758f46b2.png">

Can you provide a `Photino.Native.2.3.3-pre` build? I'll have to add this to the local feed too, to enable the restore of the dependency.

**Comment by sgacond** [comment]
@philippjbauer just another suggestion: I played and googled around about universal compilation and was able to modify your makefile to do an universal build on my arm64 mac. Should be possible on x64 machines with newest build tools too.

Makefile change:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/9912606/221342872-80323b92-6c57-4163-8c53-ec9c5960860a.png">

Result:
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/9912606/221342895-7b5b4e42-6f39-49d2-bb62-70dc1acbc068.png">

Would you appreciate a PR?

**Comment by philippjbauer** [comment]
@sgacond Thanks for pointing that out, I forgot to clear my cache when I tested the restore command with the 2.3.3-pre package. I have the dependency attached here for your LocalPackages folder:

[photino.native.2.3.3.nupkg.zip](https://github.com/tryphotino/photino.Native/files/10831435/photino.native.2.3.3.nupkg.zip)

> I played and googled around about universal compilation and was able to modify your makefile to do an universal build on my arm64 mac. Should be possible on x64 machines with newest build tools too.

I didn't consider universal packages as I thought you could only build them on an ARM64 machine. It's definitely worth trying in the pipeline build, thanks!

**Comment by sgacond** [comment]
@philippjbauer Thank you! After including the native-2.3.3 package, it restores fine now and includes the correct architecture:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/9912606/221413438-e87754ba-f7ff-4023-9e23-c137ee15a39b.png">

> I didn't consider universal packages as I thought you could only build them on an ARM64 machine. It's definitely worth trying in the pipeline build, thanks!

I'm not a clang / mac native expert but i am looking forward to your test. Would be a simpler solution than adding more and more branches. Unfortunately I don't have access to an Azure DevOps build runner to test it myself. Holding thumbs 😉.

**Comment by philippjbauer** [comment]
Hi @sgacond! We were able to successfully create a universal binary in our Azure Pipeline. While we work on a new release, you can try out the debug build:

[Photino.Native.0.9.0-20230302.5.nupkg.zip](https://github.com/tryphotino/photino.Native/files/10874012/Photino.Native.0.9.0-20230302.5.nupkg.zip)

Thank you again for your help!

**Comment by sgacond** [comment]
Thank you very much! Looking forward to the new release!
