### ISSUE TITLE
Custom settings

### ISSUE THREAD

**Issue by AnErrupTion** [tryphotino/photino.Native#94]
I'm not sure where to post this, but I'll post it here because I think it makes more sense.

I think it would be nice to be able to customize some settings (like User-Agent, or support for JavaScript, WebGL, WebRTC, those kinds of things...). An example would be reducing tracking or increasing security. As of right now, I'm not aware of anything that could let you modify any of the settings mentionned above.
I know an issue has already been opened for the User-Agent (#84), but I think we need more than that (and not separate functions, it's not convenient).

**Comment by ottodobretsberger** [comment]
It's an interesting thought, and we believe that could be very beneficial. But as with many additional features, we would rely on the community to assist with the implementation thereof, as we (unfortunately) lack the required time to put towards all of them.

**Comment by MikeYeager** [comment]
See also Photino.NET #142. 
https://www.chromium.org/developers/how-tos/run-chromium-with-flags/
https://peter.sh/experiments/chromium-command-line-switches/
https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environmentoptions?view=webview2-1.0.1901.177

**Comment by philippjbauer** [comment]
Closing as related to #116 ...
